### PR TITLE
Feature: some new staff

### PR DESCRIPTION
**Pull request by AntonRufus**
some details

### CODE REVIEW

**Comment by AntonRufus** [comment]
Looks nice, just approve the changes.

**Review by Anton-Rufus — COMMENTED** [review]
Well done.

**Review by Anton-Rufus — APPROVED** [review]
approved

**Comment by AntonRufus** [comment]
again please

**Review by Anton-Rufus — CHANGES_REQUESTED** [review]
some new changes

**Review by Anton-Rufus — APPROVED** [review]
ok, good job!

**Comment by Anton-Rufus** [comment]
nice, push it please

**Pull request merged**
